/**
 * User-facing text added from docs/SPEC-improvements.md onwards lives here, so
 * Kannada/Hindi can be added later without touching components.
 */
export const strings = {
  product: {
    name: 'Schoolinkd',
    adminTitle: 'Schoolinkd — Admin',
    adminDescription: 'Schoolinkd admin console',
    platformTitle: 'Schoolinkd — Platform',
  },
  dashboard: {
    feesCollected: 'Fees Collected',
    outstandingFees: 'Outstanding Fees',
    thisAcademicYear: (year: string | null) => (year ? `This academic year (${year})` : 'This academic year'),
  },
  paymentMethod: {
    cash: 'Cash',
    chequeOrDd: 'Cheque/DD',
    online: 'Online/UPI',
    claim: 'Claim',
  },
  attendance: {
    navLabel: 'Attendance',
    pageTitle: 'Attendance',
    rollNo: 'Roll No',
    status: { present: 'Present', absent: 'Absent', late: 'Late', leave: 'Leave' } as Record<string, string>,
    notMarked: 'Not marked',
    todayCardTitle: "Today's attendance",
    todaySummary: (present: number, total: number, pct: number | null) =>
      `${present} / ${total} present${pct != null ? ` (${pct}%)` : ''}`,
    noneMarkedYet: 'No classes marked yet today',
    allMarked: 'All classes marked',
    classesNotMarked: (n: number) => `${n} class${n === 1 ? '' : 'es'} not marked yet`,
    holidayToday: (name: string) => `Holiday today: ${name}`,
    reportTab: 'Report',
    markTab: 'Mark / Edit',
    filterClass: 'Class',
    allClasses: 'All classes',
    from: 'From',
    to: 'To',
    exportCsv: 'Export CSV (Excel)',
    columns: {
      student: 'Student',
      admissionNo: 'Admission No',
      className: 'Class',
      daysMarked: 'Days Marked',
      present: 'Present',
      late: 'Late',
      absent: 'Absent',
      leave: 'Leave',
      percentage: 'Attendance %',
    },
    noStudents: 'No students found for this filter',
    pickClassAndDate: 'Pick a class and date to mark or correct attendance.',
    date: 'Date',
    loadRoster: 'Load',
    allPresent: 'Mark all present',
    countsLine: (present: number, absent: number, other: number) =>
      `${present} present · ${absent} absent${other ? ` · ${other} late/leave` : ''}`,
    save: 'Save attendance',
    saved: 'Attendance saved',
    readOnly: 'You can view this day but not change it.',
    alreadySubmitted: 'Already submitted — saving updates it. Changes are logged.',
    holidayNoMarking: (name: string) => `${name} is a school holiday — attendance isn't taken.`,
    confirmSave: (present: number, absent: number) => `Save attendance: ${present} present, ${absent} absent?`,
  },
  holidays: {
    sectionTitle: 'School holidays',
    sectionHelp: 'Holidays are skipped when listing classes that still need attendance. Teachers cannot mark attendance on them.',
    date: 'Date',
    name: 'Holiday name',
    add: 'Add holiday',
    added: 'Holiday added',
    removed: 'Holiday removed',
    remove: 'Remove',
    empty: 'No holidays added yet',
    confirmRemove: (name: string) => `Remove the holiday "${name}"?`,
  },
  names: {
    allLowercaseWarning: 'This name is all lowercase. Check the capitalisation (e.g. "Aarav Iyer") — it will be saved exactly as typed.',
  },
} as const;
