/**
 * Product name and the marketing site's text (English only — the marketing site
 * is out of scope for docs/SPEC-languages.md). Console text lives in messages/*.json.
 */
export const strings = {
  product: {
    name: 'Schoolinkd',
    adminTitle: 'Schoolinkd — Admin',
    adminDescription: 'Schoolinkd admin console',
    platformTitle: 'Schoolinkd — Platform',
  },
  marketing: {
    metaTitle: 'Schoolinkd — Fee collection, attendance & parent app for schools',
    metaDescription:
      'Know exactly how much fee your school collected, and who still owes, every day. Cash, cheque and online payments in one dashboard, plus a parent and teacher app.',
    eyebrow: 'For school owners & principals',
    headline: 'Know exactly how much fee your school collected, and who still owes,',
    headlineHighlight: 'every single day.',
    subline:
      'Cash, cheque and online payments in one dashboard — plus a parent and teacher app for homework, notices, attendance and report cards.',
    bookDemo: 'Book a free demo on WhatsApp',
    schoolLogin: 'School Login',
    heroNote: 'Free demo · Set up in a day · We import your data for you',
    stats: [
      { value: '1 day', label: 'To go live' },
      { value: '4', label: 'Payment modes tracked' },
      { value: '0', label: 'Registers to reconcile' },
    ],
    videoEyebrow: 'Watch',
    videoTitle: 'See Schoolinkd in 90 seconds',
    videoPlay: 'Play the demo',
    videoComingSoon: 'Demo video coming soon',
    whyEyebrow: 'Why schools switch',
    whyTitle: 'Built around what keeps a school owner up at night.',
    why: [
      {
        title: 'Fewer fee defaults',
        body: 'Cash, cheque and online payments land in one place, with automatic reminders before and on the due date. You see who owes, every day.',
      },
      {
        title: 'Live in a day',
        body: 'Send us your existing Excel sheet. We import classes, students, parents and fees for you — no data entry for your staff.',
      },
      {
        title: 'Parents stay informed',
        body: 'Homework, notices, attendance with absence alerts, and report cards arrive on the parent’s phone — and you can see who opened them.',
      },
    ],
    midCtaTitle: 'See it with your own school’s numbers.',
    midCtaBody: 'A 20-minute demo on a video call or at your school. No commitment.',
    testimonialsEyebrow: 'Schools using Schoolinkd',
    testimonialsTitle: 'What principals and staff say',
    pricing: {
      eyebrow: 'Pricing',
      startingFrom: (price: string) => `Starting from ${price} per student per year`,
      simple: 'Simple per-student pricing, billed yearly',
      subtitle: 'One price covers the web console, the parent & teacher app, and onboarding.',
      included: [
        'Admin & accounts web console',
        'Parent and teacher mobile app (Android & iPhone)',
        'Online fee payments, receipts and reminders',
        'Daily attendance with absence alerts',
        'We import your existing data for free',
      ],
      cta: 'Get a quote on WhatsApp',
      multiBranch: 'Talk to us for multi-branch pricing.',
    },
    appEyebrow: 'Download the app',
    appTitle: 'Parents and teachers use the Schoolinkd app.',
    appBody: 'Sign in with the phone number registered with the school — no passwords to remember.',
    getItOn: 'Get it on',
    downloadOn: 'Download on the',
    finalTitle: 'Your next term could start on Schoolinkd.',
    finalBody: 'Book a free demo, or sign in to your school’s console.',
    contact: {
      title: 'Book a free demo',
      subtitle: 'Tell us a little about your school and we’ll call you back — or message us on WhatsApp now.',
      name: 'Your name',
      school: 'School name',
      city: 'City',
      students: 'Number of students',
      phone: 'Mobile number',
      phoneHint: '10-digit Indian mobile number',
      preferredTime: 'Preferred time to call (optional)',
      preferredTimePlaceholder: 'e.g. Weekdays after 4 pm',
      submit: 'Request a demo',
      sending: 'Sending…',
      success: 'Thank you! We’ll call you within one working day.',
      error: 'Something went wrong. Please try again, or message us on WhatsApp.',
      invalidPhone: 'Enter a valid 10-digit Indian mobile number',
      required: 'Please fill in this field',
      or: 'or',
      otherWays: 'Other ways to reach us',
    },
  },
} as const;
